apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hxbmw1juo-go 
  janus-idp.io/tekton: hxbmw1juo-go
  backstage.io/kubernetes-id: hxbmw1juo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hxbmw1juo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  