apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hxbmw1juo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hxbmw1juo-go 
  name: hxbmw1juo-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hxbmw1juo-go
    weight: 100 
